//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboard2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Onboard2DbContext : DbContext
    {
        public Onboard2DbContext()
            : base("name=Onboard2DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSold> ProductSolds { get; set; }
        public virtual DbSet<Store> Stores { get; set; }

        public System.Data.Entity.DbSet<Onboard2.Models.MyProduk> MyProduks { get; set; }

        public System.Data.Entity.DbSet<Onboard2.Models.MyCustomer> MyCustomers { get; set; }

        public System.Data.Entity.DbSet<Onboard2.Models.MyStore> MyStores { get; set; }

        public System.Data.Entity.DbSet<Onboard2.Models.MySale> MySales { get; set; }
    }
}
